### ISSUE TITLE
broken area name for S7

### ISSUE THREAD

**Issue by sieger82** [bkerler/sboot_dump#1]
on an S7, the area name for area 12 has some null characters appended tot it, this breaks the memdump.
in commit ed29f031f21d374e103c9c75f5bb0208263e6d09 it still works...

Probed device:
---------------
64-Bit, Devicename: "SM-G930F"

Detected upload areas:
---------------------
0: "kernel debug" (0x91a00000,0x91bfffff)
1: "platform deb" (0x91c00000,0x91ffffff)
2: "radio debug" (0x92000000,0x921fffff)
3: "sfr debug" (0x92200000,0x925fffff)
4: "etm debug" (0x92600000,0x92dfffff)
5: "tima" (0x92e02000,0x93001fff)
6: "kaslr" (0x80001000,0x80001fff)
7: "el2" (0xb0600000,0xb063ffff)
8: "avc" (0x93004000,0x93043fff)
9: "tsp" (0x93046000,0x93085fff)
10: "auto_comment" (0x93088000,0x93088f3b)
11: "ap" (0x80000000,0xbfffffff)
12: "ap
       " (0xc0000000,0xfe3fffff)
13: "ap" (0x880000000,0x8bfffffff)
14: "ap" (0x8c0000000,0x8ffffffff)
15: "cp" (0xf0000000,0xf7ffffff)
16: "ap_cp" (0xf8000000,0xf87fffff)

**Comment by bkerler** [comment]
Thanks, will seek into it

**Comment by bkerler** [comment]
Solved with commit 560e7fd3b1d41f4d10fb112ae3a546fdadf1a939
