### ISSUE TITLE
Dumping process keeps timing out or hanging for Spreadtrum / Qualcomm Devices

### ISSUE THREAD

**Issue by inkstray** [bkerler/sboot_dump#2]
I tried dumping all memory regions on my Galaxy J4+ (Qualcomm) but seemingly the first attempt times out and the attempt second gets stuck at 25% somehow.

On my Galaxy J3 (2016) SM-J320FN (Spreadtrum) it keeps giving timeout errors and it takes ages to dump.

I got into upload mode on these devices by enabling some stuff in a menu that can be accessed using the dialer... The code is ``*#9900#``
from the menu: Set debug level to high and enable upload mode (if option is there), then reboot and do a power reset (holding VOL DOWN + POWER or VOL DOWN + POWER + HOME)

**Comment by mfn003** [comment]
Can confirm with my Galaxy J1 ace _(SM-J110H)_ which is powered by a Spreadtrum SC7727S.

**Comment by itsvic-dev** [comment]
can confirm with my Galaxy J6+ (SM-J610FN/DS), which complained about timeout errors before hanging on 25%

![image](https://user-images.githubusercontent.com/17727163/182417311-9b83c2ff-8daa-4f78-ab78-2f7047ab8f72.png)

**Comment by bkerler** [comment]
Samsung might use a different structure for spreadtrum. Will try and get one soon

**Comment by kraftdenker** [comment]
In Galaxy S20 FE (Qualcomm), reading RAM partition [47:"dram_cs0" (0x80000000,0xffffffff)], it just reads the first 512 bytes and stucks at the second block reading. I also tried adapting code to read using serial COM, but it also hangs after reading 1.200k.
I cutted out the 32k read size limit control (comments in lines 627/628   #if size > 0x80000: # size = 0x80000), and it worked :)

**Comment by bkerler** [comment]
@kraftdenker can you please test the latest code if you still need to remove the size limitation ?

**Comment by kraftdenker** [comment]
> @kraftdenker can you please test the latest code if you still need to remove the size limitation ?

@bkerler , Unfortunately I still need to remove the size limitation.

**Comment by ceckoslab** [comment]
I think that it worked fine for me with Samsung Galaxy J5 . The challenge was to set the phone in Upload mode.

I really had to use the trick with `*#9900#`. I dialed `*#9900#` and from the secret menu set debug level to high.

VOL DOWN + POWER + HOME set the phone in upload mode:

![upload mode](https://user-images.githubusercontent.com/1024001/206586376-57a239cd-4ae7-47bc-9a66-b730baa13973.jpg)

It was dumping for less than 2 hours and I got:
```
-rw-rw-r-- 1 tsvetan tsvetan 1044381696 Dez  7 23:10  ap_40000000_7e3fffff.lst
-rw-rw-r-- 1 tsvetan tsvetan 1073741824 Dez  7 23:56  ap_80000000_bfffffff.lst
-rw-rw-r-- 1 tsvetan tsvetan    4194304 Dez  8 00:02  ap_cp_b7400000_b77fffff.lst
-rw-rw-r-- 1 tsvetan tsvetan       3900 Dez  7 22:25  auto_comment_46f90000_46f90f3b.lst
-rw-rw-r-- 1 tsvetan tsvetan     262144 Dez  7 22:25  avc_46e0a000_46e49fff.lst
-rw-rw-r-- 1 tsvetan tsvetan  121634816 Dez  8 00:02  cp_b0000000_b73fffff.lst
-rw-rw-r-- 1 tsvetan tsvetan     262144 Dez  7 22:25  el2_52300000_5233ffff.lst
-rw-rw-r-- 1 tsvetan tsvetan    2097152 Dez  7 22:25 'kernel debug_46800000_469fffff.lst'
-rw-rw-r-- 1 tsvetan tsvetan    4194304 Dez  7 22:25 'platform deb_46a00000_46dfffff.lst'
-rw-rw-r-- 1 tsvetan tsvetan      32768 Dez  7 22:25 'pstore debug_46e00000_46e07fff.lst'
-rw-rw-r-- 1 tsvetan tsvetan    2097152 Dez  7 22:25  tima_52a00000_52bfffff.lst
-rw-rw-r-- 1 tsvetan tsvetan     262144 Dez  7 22:25  tsp_46e4c000_46e8bfff.lst
```
I browsed with hexeditor the files and could see some plain text.

**Comment by bkerler** [comment]
Closing as I assume it is fixed by now.
