### ISSUE TITLE
Galaxy Core GT-I8260 "Couldn't detect the device. Is it connected ?"

### ISSUE THREAD

**Issue by inkstray** [bkerler/sboot_dump#3]
My Samsung Galaxy Core doesn't seem to recognised when in RAMDUMP (ARM9 Mode)
``lsusb`` reveals:
```Bus 001 Device 014: ID 04e8:6640 Samsung Electronics Co., Ltd Usb Modem Enumerator```

Could you perhaps add support for devices using ARM9 Mode?

(I want to collect bootloader logs for analyzing.. they are usually stored in last_kmsg but they forgot to enable the feature with the kernel. so now my last option is RAMDUMP/ARM9 Mode.)
my intention was to do this without having to unlock the bootloader.

**Comment by bkerler** [comment]
Can you be please more specific what you mean with ramdump/arm9 mode ?

**Comment by bkerler** [comment]
I guess you mean the qc ramdump .. for that, please use my "edl" tool

**Comment by inkstray** [comment]
> I guess you mean the qc ramdump .. for that, please use my "edl" tool

yeah i forgot to respond my bad... but yes thats what i meant
ill be sure to check it out thx

**Comment by bkerler** [comment]
Closing this issue for now, reopen if necessary.
